<script lang="ts">
	import { ArrowUpRight, Bug, Lightbulb, Map, ShieldAlert } from '@lucide/svelte';
	import { Area, Button, Header, NavItem } from '@arcivo/ui-components';
	const forgejoUrl = 'https://git.heiserer.de/Arcivo/Arcivo';
	const issuesUrl = `${forgejoUrl}/issues`;
	const issues = [
		{ number: 43, title: 'Gotenberg security change', category: 'Bug', icon: ShieldAlert, summary: 'Harden document conversion against unwanted internal network requests.' }, { number: 42, title: 'Rate limiting', category: 'In progress', icon: Map, summary: 'Protect the login flow with sensible request limits.' }, { number: 38, title: 'PDF not rendering in Safari', category: 'Bug', icon: Bug, summary: 'Improve document viewing on Safari.' }, { number: 29, title: 'External sharing and guest upload', category: 'Concept', icon: Lightbulb, summary: 'Time-limited sharing links and secure upload portals.' }, { number: 28, title: 'Automatic document classification', category: 'Concept', icon: Lightbulb, summary: 'Suggest useful metadata, tags, and document types.' }, { number: 27, title: 'Watched-folder ingestion', category: 'Concept', icon: Lightbulb, summary: 'Import documents from folders automatically.' }, { number: 26, title: 'Email ingestion', category: 'Concept', icon: Lightbulb, summary: 'Turn important incoming email into archive records.' }, { number: 32, title: 'Mobile document capture', category: 'Concept', icon: Lightbulb, summary: 'Capture, upload, find, and access documents on mobile.' }, { number: 31, title: 'Windows desktop client', category: 'Concept', icon: Lightbulb, summary: 'Bring Arcivo into Windows File Explorer.' }, { number: 30, title: 'Linux desktop client', category: 'Concept', icon: Lightbulb, summary: 'Native-feeling access and upload for GNOME desktops.' }
	];
</script>
<svelte:head><title>Roadmap & issues · Arcivo</title><meta name="description" content="Follow Arcivo development through its public Forgejo issues and roadmap." /></svelte:head>
<main><section class="page-header"><div class="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><Header level={1} title="Roadmap and issues" description="Selected work from the public Arcivo Forgejo tracker." /><Button href={issuesUrl} variant="outline" target="_blank" rel="noreferrer">All issues {#snippet trailing()}<ArrowUpRight size={15} />{/snippet}</Button></div></section><section class="mx-auto max-w-6xl px-5 pb-16 sm:px-8"><div class="grid gap-8 lg:grid-cols-[0.32fr_0.68fr]"><div><Header title="Open work" description="Every item links directly to its Forgejo issue." /><p class="text-sm leading-6 text-neutral-500 dark:text-neutral-400">Forgejo remains the source of truth for status, discussion, and the complete issue list.</p></div><Area title="Selected issues" description="Current fixes and longer-term feature concepts."><div class="grid gap-1">{#each issues as issue}{@const Icon = issue.icon}<NavItem href={`${issuesUrl}/${issue.number}`} label={`#${issue.number} · ${issue.title}`} description={issue.summary} badge={issue.category} title={`Open issue #${issue.number} in Forgejo`}>{#snippet leading()}<span class="issue-icon"><Icon size={17} /></span>{/snippet}</NavItem>{/each}</div></Area></div></section></main>
