<script lang="ts">
	import { Archive, CheckCircle2, FileSearch, Files, FolderTree, Grid2X2, Keyboard, ScanText, ShieldCheck, Tag, Upload } from '@lucide/svelte';
	import type { Component } from 'svelte';
	import { Area, Button, Header } from '@arcivo/ui-components';
	type FeatureGroup = { title: string; description: string; items: [string, string, Component<{ size?: number }>] [] };
	const featureGroups: FeatureGroup[] = [
		{ title: 'Capture and preserve', description: 'Bring documents in confidently and keep a durable record.', items: [['Drag-and-drop upload', 'Drop files anywhere in the workspace or use the uploader.', Upload], ['Broad file support', 'Handle PDFs, Office files, images, archives, and more.', Files], ['PDF/A conversion', 'Generate archival PDF/A versions for long-term preservation.', Archive], ['Document versions', 'Keep historical versions alongside the original document.', FolderTree]] },
		{ title: 'Find what you need', description: 'Turn a stack of files into information you can retrieve.', items: [['Full-text search', 'Search extracted document text as well as filenames.', FileSearch], ['Text extraction', 'Read content from supported documents automatically.', ScanText], ['Thumbnails and previews', 'Recognise documents at a glance before opening them.', Grid2X2], ['Keyboard-first navigation', 'Use shortcuts such as Ctrl K to move faster.', Keyboard]] },
		{ title: 'Keep control', description: 'A focused experience that respects your data and your preferences.', items: [['Metadata and tags', 'Add the context that makes an archive work for you.', Tag], ['List and grid views', 'Choose the detail and density that suits the task.', Grid2X2], ['Checksum deduplication', 'Avoid accidental duplicates during upload.', CheckCircle2], ['Self-hosted privacy', 'Run Arcivo on infrastructure you own, with no subscription.', ShieldCheck]] }
	];
</script>
<svelte:head><title>Features · Arcivo</title><meta name="description" content="Explore Arcivo's main document management features." /></svelte:head>
<main><section class="page-header"><Header level={1} title="Features" description="The main capabilities currently available in Arcivo." /></section><section class="mx-auto max-w-6xl px-5 pb-16 sm:px-8"><div class="space-y-6">{#each featureGroups as group}<Area title={group.title} description={group.description}><div class="grid gap-x-7 sm:grid-cols-2 sm:divide-x sm:divide-neutral-100 dark:sm:divide-neutral-800">{#each group.items as item, index}{@const Icon = item[2]}<article class="feature-row {index > 1 ? 'border-t border-neutral-100 dark:border-neutral-800' : ''}"><div class="feature-row-icon"><Icon size={18} /></div><div><h2>{item[0]}</h2><p>{item[1]}</p></div></article>{/each}</div></Area>{/each}</div><div class="mt-8 flex items-center justify-between gap-4 border-t border-neutral-200 pt-8 dark:border-neutral-800"><p class="text-sm text-neutral-500 dark:text-neutral-400">Planned capabilities are documented in the public issue tracker.</p><Button href="/roadmap" variant="outline">View roadmap</Button></div></section></main>
